### ISSUE TITLE
Disable Sounds

### ISSUE THREAD

**Issue by LexikonALM** [tobykurien/rpi_lcars#10]
I love the work you have done here. Admittedly I am very inexperienced when it comes to any sort of programming. I just sorta jump into it, but I can follow directions very slowly figure things out.

My questions is: How can I disable lcars from using or configuring any sound settings. I currently have my pi setup with an IQaudIODAC sound card hat which I use to Airplay music from my phone to my pi. When I execute the script to run lcars, my music no longer plays through my speakers (no sounds play that are supposed to occur when pushing buttons in lcars but that is a much smaller issue to me). If they both played their sounds accordingly that would be super, but I imagine it would take a lot more tweaking to get that to happen then to just prevent lcars from overriding the airplay program that I have running. 
 
Okay...small edit to my question. 

I figured out how to change the UI setting so now I am getting the LCARS sound effects as intended through my speakers now via my IQaudIODAC+ .
But my music will still not play when LCARS is running.

**Comment by tobykurien** [comment]
There isn't currently a setting to disable the audio. You'd have to comment out the the audio initialization in https://github.com/tobykurien/rpi_lcars/blob/master/app/ui/ui.py and also comment out the calls to play audio within the screens.
