### ISSUE TITLE
Install issue: missing module?

### ISSUE THREAD

**Issue by roguepullrequest** [tobykurien/rpi_lcars#19]
On pi3 with latest updates and freashest git repo. 
After running ´setup.sh´ move over into the ´app´ dir and run ´python lcars.py´ 

´´´ 
...
      from ui.utils import sound
ImportError: no module named utils
´´´

Been poking around but cant see where exactly what is missing to be installed.

**Comment by tobykurien** [comment]
Does the 'app/ui/utils' directory exist? Does this file exist: 'app/ui/utils/__init__.py'? All I can think of is that maybe the git clone did not complete.

**Comment by roguepullrequest** [comment]
Thanks for getting back. 

Yeah the dir exists but your broken clone idea was good. Removed the old repo and recloned. Still getting same error. 

`pi@raspberrypi:~/git/lcars_rpi$ ls -lathr app/ui/utils/
total 60K
-rw-r--r-- 1 pi pi 1.5K Feb 22 02:19 sound.py
-rw-r--r-- 1 pi pi 8.7K Feb 22 02:19 interpolator.py
-rw-r--r-- 1 pi pi    0 Feb 22 02:19 __init__.py
-rw-r--r-- 1 pi pi 6.0K Feb 22 02:19 gif_image.py
-rw-r--r-- 1 pi pi 2.8K Feb 22 05:07 sound.pyc
-rw-r--r-- 1 pi pi  134 Feb 22 05:07 __init__.pyc
-rw-r--r-- 1 pi pi 8.1K Feb 22 05:07 interpolator.pyc
-rw-r--r-- 1 pi pi 6.1K Feb 22 05:07 gif_image.pyc
drwxr-xr-x 2 pi pi 4.0K Feb 22 05:07 .
drwxr-xr-x 4 pi pi 4.0K Feb 22 05:07 ..
pi@raspberrypi:~/git/lcars_rpi$ ls -lathr app/ui/utils/*init* 
-rw-r--r-- 1 pi pi   0 Feb 22 02:19 app/ui/utils/__init__.py
-rw-r--r-- 1 pi pi 134 Feb 22 05:07 app/ui/utils/__init__.pyc
pi@raspberrypi:~/git/lcars_rpi$ cd ../
pi@raspberrypi:~/git$ rm -rf lcars_rpi && git clone https://github.com/tobykurien/rpi_lcars lcars_rpi
Cloning into 'lcars_rpi'...
remote: Enumerating objects: 359, done.
remote: Total 359 (delta 0), reused 0 (delta 0), pack-reused 359
Receiving objects: 100% (359/359), 2.74 MiB | 111.00 KiB/s, done.
Resolving deltas: 100% (167/167), done.
pi@raspberrypi:~/git$ ls
dotfiles  ghostwriter  lcars_rpi  programmer-dvorak  protonvpn-cli  qmk
pi@raspberrypi:~/git$ cd lcars_rpi/
pi@raspberrypi:~/git/lcars_rpi$ ls 
app   demo     README.md	 run.sh		 setup.sh
boot  LICENSE  requirements.txt  screenshot.png
pi@raspberrypi:~/git/lcars_rpi$ bash ./setup.sh 
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease                  
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]     
Fetched 15.0 kB in 24s (614 B/s)                                               
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenjp2-7-dev is already the newest version (2.1.2-1.1+deb9u2).
python3 is already the newest version (3.5.3-1).
python3-pip is already the newest version (9.0.1-2+rpt2).
The following package was automatically installed and is no longer required:
  realpath
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already satisfied: pygame>=1.9.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: psutil in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xinit is already the newest version (1.3.4-3).
The following package was automatically installed and is no longer required:
  realpath
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
pi@raspberrypi:~/git/lcars_rpi$ cd app
pi@raspberrypi:~/git/lcars_rpi/app$ python 
assets/      config.py    datasources/ lcars.py     screens/     ui/
pi@raspberrypi:~/git/lcars_rpi/app$ python lcars.py 
Traceback (most recent call last):
  File "lcars.py", line 2, in <module>
    from ui.ui import UserInterface
  File "/home/pi/git/lcars_rpi/app/ui/ui.py", line 4, in <module>
    from ui.utils import sound
ImportError: No module named utils
pi@raspberrypi:~/git/lcars_rpi/app$`

**Comment by tobykurien** [comment]
Could you try `python3 lcars.py` in case there are multiple versions of python

**Comment by roguepullrequest** [comment]
Looks likes that works for the most part. 
´pygame.error: Couldn't set hardware audio parameters: Success´ 
Is the new issue if ´SOUND = True´ in ´app/config.py´
