### ISSUE TITLE
traceback issue

### ISSUE THREAD

**Issue by BjornOR** [tobykurien/rpi_lcars#24]
pi@raspberrypi:~/rpi_lcars-master/app $ sudo python lcars.py
Traceback (most recent call last):
  File "lcars.py", line 2, in <module>
    from ui.ui import UserInterface
  File "/home/pi/rpi_lcars-master/app/ui/ui.py", line 4, in <module>
    from ui.utils import sound
ImportError: No module named utils
__

For some reason I can't get this to work on my raspberry pi 3B plus

**Comment by dgw** [comment]
Sounds like a duplicate of #19

**Comment by BjornOR** [comment]
the answer was sudo python3 lcars.py
