### ISSUE TITLE
Nothing, blank screen

### ISSUE THREAD

**Issue by devilwacause** [tobykurien/rpi_lcars#25]
When I run sudo python3 lcars.py, 

I get nothing, just a black screen on the display. 

No errors in the console (I'm ssh'd in) any ideas?

On cancel (ctrl + c) I get the following

```
Traceback (most recent call last):
  File "lcars.py", line 11, in <module>
    ui.tick()
  File "/home/pi/Desktop/LCARS_Python/rpi_lcars/app/ui/ui.py", line 66, in tick
    self.update()
  File "/home/pi/Desktop/LCARS_Python/rpi_lcars/app/ui/ui.py", line 37, in update
    pygame.display.update()
```

Thanks.

**Comment by dgw** [comment]
If you figured out a solution, it would be helpful to future users if you could summarize here what the fix was. :smile_cat:

**Comment by devilwacause** [comment]
I'm not quite sure what I did as I was changing several variables over time (I'm more a web programmer by trade and have never taken the time to sit down with Python) 

I believe it was turning DEV_MODE = FALSE.
But do not hold me to that answer.  Also between the change and the chance to test I was in and out of "developer mode" and "daddy mode" so I could have changed something else.

I will be opening another ticket for a secondary issue however, and am hoping I found the solution to it last night.  Will be working on it today.

**Comment by JDat** [comment]
I am curious what you are expecting from remote SSH console while LCARS is GUI software. Or... I missed something.

**Comment by devilwacause** [comment]
I'm not expecting anything in the console.  I have a 10.1 inch touch screen attached to the pi, I ssh in to do code as swapping the keyboard gets tedious.  The lcars app loads on the touchscreen

**Comment by tobykurien** [comment]
If you're ssh'ing in you'd usually have to set the DISPLAY environment variable to tell the program where to output the GUI otherwise it tries to draw the GUI in the ssh console, which fails. Not sure how it ended up working for you.

**Comment by devilwacause** [comment]
Assuming you are talking about the SDL_VIDEODRIVER environment variable ->
When not set the SDL_VIDEODRIVER goes thru available options til the first one is found that works.

![image](https://user-images.githubusercontent.com/24920886/62123932-a2ec3500-b28e-11e9-9765-3192d6054e27.png)


![67661934_468630433969069_5872944911979905024_n](https://user-images.githubusercontent.com/24920886/62123310-43d9f080-b28d-11e9-85c0-ed7ea7a97ff9.jpg)


and the libpng warning is over modification of the screen background to match the dimensions of my screen.  I just havent run it thru Imagick to clear the unsupported information.
