### ISSUE TITLE
Will not fill 7" touchscreen

### ISSUE THREAD

**Issue by acemasterhan** [tobykurien/rpi_lcars#28]
Using a Pi 4 and a 7" touchscreen with a resolution of 1024x600

No matter what I do the lcars will not fill the screen. It is always too small and in the upper left corner. 

I have tried editing  /boot/config.txt , /app/config.py , /ui/ui.py  etc. None of it seems to make any difference. I'm not sure what I'm missing but it will never be centered and fill the screen. 

Any help would be greatly appreciated.

**Comment by JGBrake** [comment]
How is the hardware setup go ?

**Comment by acemasterhan** [comment]
HDMI for the video, usb for the touch screen functionality. 

This is the monitor:  https://www.amazon.com/Eviciv-Portable-Monitor-Display-1024X600/dp/B07L6WT77H

This is how I have it connected if that helps

![image](https://user-images.githubusercontent.com/52250213/85464725-f7b72f00-b575-11ea-9d09-67a0d139cd06.png)

**Comment by acemasterhan** [comment]
Also for the record this is what I'm seeing. As you can see it does not fill the screen. 

![IMG_20200623_175548](https://user-images.githubusercontent.com/52250213/85469283-7793c800-b57b-11ea-828f-febf9071558f.jpg)

**Comment by JGBrake** [comment]
Maybe try setting with in the lacars? Or try connecting it to a normal tv and see if it does the same thing.

**Comment by acemasterhan** [comment]
After doing some searching it seems that it's just not made to scale to higher resolutions.

**Comment by dgw** [comment]
Resolution scaling would make a great feature request, wouldn't it? If you wanted to pivot (retitle) this issue, or make a new one.

**Comment by tobykurien** [comment]
Yes I can confirm, to keep things simple, the resolution is fixed. It is meant for the official pi touchscreen.

**Comment by tobykurien** [comment]
One solution would be to run your screen at 800x480 resolution.
