### ISSUE TITLE
python-pil package not available in default repositories

### ISSUE THREAD

**Issue by cokelid** [tobykurien/rpi_lcars#3]
In `setup.sh` you install the `python-pil` package.
On a vanilla and up-to-date RPi installation this package doesn't exist. Is there a custom repository that needs to be added?
I tried using the `python-imaging` package in its place, but that doesn't work (`image.tobytes()` does not exist).
Do we need the regular Pything Imaging Library, or Pillow perhaps?
Cheers,
Justin

**Comment by tobykurien** [comment]
Can you try changing ```image.tobytes()``` to ```image.tostring()``` and try with the ```python-imaging``` package?

**Comment by cokelid** [comment]
OK - I did:
`sudo apt-get install python-imaging`
And then changed `image.tobytes()` to `image.tostring()` in `apps/utils/gif_image.py` and it works!

I do see that the animation under the "SENSORS" button is not displaying properly, though this might be a separate issue? The "forward sensors" animation is working fine however.

Thanks for the prompt reply!

**Comment by tobykurien** [comment]
Thanks for the feedback, I'll see if I can make the setup work for either package - seems like different versions of raspbian support different package names and versions.
