### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by MCDevel** [tobykurien/rpi_lcars#32]
i always become the erro massege 
(EE) 
Fatal server error:
(EE) Server is already active for display 0
	If this server is no longer running, remove /tmp/.X0-lock
	and start again.
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) 

when i starte the lcars

**Comment by tobykurien** [comment]
The run.sh script assumes that you booted into command line mode, if you are already in desktop mode, you can remove 'xinit' from the run.sh file.

**Comment by DansDesigns** [comment]
All I had to do was add `needs_root_rights = yes` to `/etc/X11/Xwrapper.config` and plain xinit worked. (even though needs_root_rights=yes sounds a little contrary to the error message I was getting lol)
