### ISSUE TITLE
Autostarte

### ISSUE THREAD

**Issue by MCDevel** [tobykurien/rpi_lcars#33]
how can i make the lcars so that it autostart. i tryed many ways but it is not working

**Comment by tobykurien** [comment]
It is described in the README:

https://github.com/tobykurien/rpi_lcars#launching

**Comment by MCDevel** [comment]
it still not work. it want autostart

**Comment by tobykurien** [comment]
Could you please post details like what you tried and any errors?

**Comment by MCDevel** [comment]
I did the modify to the root Datei and reboot the raspberry pi bit i doesn't Start automatic

**Comment by JDat** [comment]
1st thing: are you booting to console or to graphical environment?

If CLI
Please read carefully readme and google how to modify /etc/crontab or /etc/rc.local. Better solution is to use systemd service, but it will be too hard for linux beginner.
else
In graphical environment there is (don't remember exact name for tool  (default programs or startup programs or similar), google it) desktop configuration where is autorun setting for GUI.
