### ISSUE TITLE
#40 not solved

### ISSUE THREAD

**Issue by MCDevel** [tobykurien/rpi_lcars#41]
Youl cloesed in for mention a nother issu but i tryed the solution but it still not working
#40

**Comment by JDat** [comment]
Additionaly to #38
1) cd to lcars folder
2) run "python3 lcars.py" or whatever it was.

I wonder why it always works for me and not working for others. And, yes, it runs as soon as I install pygame on clean raspbian...
Am I doing something in "wrong way" or I simply like to look little deeper if something not working...

**Comment by MCDevel** [comment]
idk ether why i won't work i did everything you wrote and when i start the following message apear:
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
File "lcars.py", line 2, in
from ui.ui import UserInterface
File "/home/pi/rpi_lcars-master/app/ui/ui.py", line 4, in
from ui.utils import sound
ImportError: No module named utils

**Comment by tobykurien** [comment]
@MCDevel Please don't keep adding issues, you are welcome to keep the discussion on the thread I referenced which is #38. That one is not closed, because the issue still exists for certain people.
