### ISSUE TITLE
This is more a question than an issue

### ISSUE THREAD

**Issue by wildbi111** [tobykurien/rpi_lcars#8]
In which file do you configure the touch buttons?  When I run rpi_lcars I get to the "Authorization Required" screen, which I touch and then see eight buttons appear at the bottom, none of which do anything.  Also, I still see "Authorization Required".  So I am at a loss on what to do at this point.

Bill Richards
RPi3 w/Touch Screen

**Comment by wildbi111** [comment]
On further tinkering, 3 taps on the butons takes me back to the original screen without buttons.

**Comment by tobykurien** [comment]
See `app/screens/authorize.py` line 55, where the pin code is set. It's just an example screen of how you might implement a pin lock.

**Comment by tobykurien** [comment]
This could have been related to #9 - so closing
