### ISSUE TITLE
Buttons not working on main screen

### ISSUE THREAD

**Issue by jeffg2k** [tobykurien/rpi_lcars#9]
After the change from authorize to main, the buttons no longer work.  I tracked it down to turning off DEV_MODE, which sets pygame.mouse.set_visible(False).

Not sure why, but that is causing my touch screen to loose the button somehow, though it makes the sound as if I touched the screen.

I was able to resolve it by changing the set_visible(False) instead to this, which makes the cursor invisible.

pygame.mouse.set_cursor((8,8),(0,0),(0,0,0,0,0,0,0,0),(0,0,0,0,0,0,0,0))

**Comment by jeffg2k** [comment]
Another problem is UI_PLACEMENT_MODE.  It's excluding the button down and up in the Sprite.py so buttons don't work correctly when this is False.  

if self.groups()[0].UI_PLACEMENT_MODE: should only apply to the pygame.MOUSEMOTION statement.

**Comment by tobykurien** [comment]
Thanks for the info @jeffg2k - which touch screen are you using? I suspect newer versions of pygame may have changed things a bit. I might have to pin the older versions I used.

**Comment by jeffg2k** [comment]
It's the standard Raspberry Pi 7" Touchscreen Display https://www.raspberrypi.org/products/raspberry-pi-touch-display/
